name: ppn_pysteps14
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.7
  - git
  - numpy
  - scipy
  - h5py
  - pillow
  - pysteps=1.4
  - dask
  - pyfftw
  - eccodes
  - pip
  - pip:
    - eccodes